export const ERROR_CODES = {
  AUTH_REQUIRED: "AUTH_REQUIRED",
  RBAC_DENIED: "RBAC_DENIED",
  VALIDATION_FAILED: "VALIDATION_FAILED",
  RATE_LIMITED: "RATE_LIMITED",
  NETWORK_OFFLINE: "NETWORK_OFFLINE",
  SYNC_WRITE_FAILED: "SYNC_WRITE_FAILED",
  VERSION_CONFLICT: "VERSION_CONFLICT",
  LESSON_CONTENT_CHANGED: "LESSON_CONTENT_CHANGED",
  RECORD_MERGE_CONFLICT: "RECORD_MERGE_CONFLICT",
  MIGRATION_REQUIRED: "MIGRATION_REQUIRED"
} as const;

export type ErrorCode = keyof typeof ERROR_CODES;
