export const ERROR_CODES = {
  AUTH_REQUIRED: "AUTH_REQUIRED",
  RBAC_DENIED: "RBAC_DENIED",
  VALIDATION_FAILED: "VALIDATION_FAILED",
  RATE_LIMITED: "RATE_LIMITED",
  // —— 离线同步链路错误码 ——
  SYNC_OFFLINE: "SYNC_OFFLINE",
  SYNC_CONFLICT: "SYNC_CONFLICT",
  SYNC_FAILED: "SYNC_FAILED",
  SYNC_QUEUE_FULL: "SYNC_QUEUE_FULL",
  SYNC_IDEMPOTENT_MISMATCH: "SYNC_IDEMPOTENT_MISMATCH",
  LESSON_VERSION_STALE: "LESSON_VERSION_STALE",
  MIGRATION_FAILED: "MIGRATION_FAILED",
  OUTBOX_WRITE_FAILED: "OUTBOX_WRITE_FAILED"
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];
